use serde::{Deserialize, Serialize};

#[derive(Serialize,  Deserialize, Clone, Debug)]
pub struct DetectorConfig {
    pub integration_time: u64,
    pub num_dark_images: i64,
    pub preview: u8,
    pub hold_on_prep: i64,
    pub min_charge: i64,
    pub dc_offset: i64,
    pub diag_type: u64,
    pub inactivity_timeout: i64,
    pub capture_mode: u64,
    pub number_images_in_sequence: i64,
    pub top_border: i64,
    pub bottom_border: i64,
    pub left_border: i64,
    pub right_border: i64,
    pub offset_adjustment_correction: i64,
    pub gain_correction: u8,
    pub defect_correction_on: u8,
    pub grid_correction: u8,
    pub trigger_source: i64,
    pub beam_prep_timer: i64,
    pub beam_idle_timer: i64,
    pub beam_exit_timer: i64,
    pub fast_preview_on: u8,
    pub warning_charge: i64,
    pub backup_battery_min_charge: i64,
    pub hs_data_path: String,
    pub binning_mode: i64,
    pub tomo_min_panel_warmup: u32,
    pub inter_tomo_rest_time: i64,
    pub delete_on_xfer_complete: u8,
    pub image_ready_delivery: u8,
    pub max_stored_images: i64,
    pub silent: u8,
}
impl Default for DetectorConfig {
    fn default() -> Self {
        Self { 
            integration_time: 1000, 
            num_dark_images: 2, 
            preview: 1, 
            hold_on_prep: 20, 
            min_charge: 10, 
            dc_offset: 256, 
            diag_type: 3,
            inactivity_timeout: 0, 
            capture_mode: 0,
            number_images_in_sequence: 1, 
            top_border: 8, 
            bottom_border: 8, 
            left_border: 8, 
            right_border: 8, 
            offset_adjustment_correction: 1, 
            gain_correction: 1, 
            defect_correction_on: 0, 
            grid_correction: 1, 
            trigger_source: 0, 
            beam_prep_timer: 0, 
            beam_idle_timer: 0, 
            beam_exit_timer: 60, 
            fast_preview_on: 1, 
            warning_charge: 5, 
            backup_battery_min_charge: 3500, 
            hs_data_path: 0.to_string(), 
            binning_mode: 0, 
            tomo_min_panel_warmup: 2000, 
            inter_tomo_rest_time: 10, 
            delete_on_xfer_complete: 0, 
            image_ready_delivery: 1, 
            max_stored_images: 100, 
            silent: 0 
        }
    }
}